import { ContractConversation, ChatMessage } from '@/types/chat';

export const INITIAL_CONVERSATIONS: ContractConversation[] = [
  {
    contractId: '101',
    projectTitle: 'Smart Contract Security Audit & Optimizations',
    jobId: 'JOB-9042',
    contractStatus: 'active',
    totalAmount: '2,500',
    currency: 'XLM',
    client: {
      id: 'client_1',
      name: 'Alex Vance',
      username: 'alexvance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      role: 'client',
      walletAddress: 'GCXB...9942',
      online: true,
    },
    freelancer: {
      id: 'freelancer_1',
      name: 'Elena Rostova',
      username: 'erostova',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      role: 'freelancer',
      walletAddress: 'GA7P...3310',
      online: true,
    },
    lastMessage: {
      content: 'I have uploaded the initial audit report draft for Milestone 1.',
      timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      senderId: 'freelancer_1',
    },
    unreadCount: 2,
    updatedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    contractId: '102',
    projectTitle: 'Stellar Soroban Frontend Integration',
    jobId: 'JOB-8819',
    contractStatus: 'in_progress' as any,
    totalAmount: '4,000',
    currency: 'USDC',
    client: {
      id: 'client_1',
      name: 'Alex Vance',
      username: 'alexvance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      role: 'client',
      walletAddress: 'GCXB...9942',
      online: true,
    },
    freelancer: {
      id: 'freelancer_2',
      name: 'Marcus Chen',
      username: 'mchen_dev',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
      role: 'freelancer',
      walletAddress: 'GB99...4401',
      online: false,
    },
    lastMessage: {
      content: 'The Freighter wallet connection hook is working smoothly now!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      senderId: 'client_1',
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    contractId: '103',
    projectTitle: 'Decentralized Escrow Architecture Specification',
    jobId: 'JOB-7410',
    contractStatus: 'completed',
    totalAmount: '1,800',
    currency: 'XLM',
    client: {
      id: 'client_2',
      name: 'Sarah Jenkins',
      username: 'sjenkins',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
      role: 'client',
      walletAddress: 'GD55...1109',
      online: false,
    },
    freelancer: {
      id: 'freelancer_1',
      name: 'Elena Rostova',
      username: 'erostova',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      role: 'freelancer',
      walletAddress: 'GA7P...3310',
      online: true,
    },
    lastMessage: {
      content: 'Funds have been released successfully. Thank you for working together!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      senderId: 'client_2',
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  '101': [
    {
      id: 'msg_101_1',
      contractId: '101',
      senderId: 'client_1',
      senderName: 'Alex Vance',
      senderRole: 'client',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      content: 'Hi Elena! Excited to get started on the Soroban smart contract security audit.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_101_2',
      contractId: '101',
      senderId: 'freelancer_1',
      senderName: 'Elena Rostova',
      senderRole: 'freelancer',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      content: 'Hello Alex! I have received access to the GitHub repository and Soroban contracts code. Initial static analysis is underway.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3.5).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_101_3',
      contractId: '101',
      senderId: 'client_1',
      senderName: 'Alex Vance',
      senderRole: 'client',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      content: 'Great. Pay close attention to the re-entrancy and auth check logic in the escrow release handler.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_101_4',
      contractId: '101',
      senderId: 'freelancer_1',
      senderName: 'Elena Rostova',
      senderRole: 'freelancer',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      content: 'Understood. I found 2 minor recommendations for gas optimization and verified the require_auth() checks.',
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_101_5',
      contractId: '101',
      senderId: 'freelancer_1',
      senderName: 'Elena Rostova',
      senderRole: 'freelancer',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      content: 'I have uploaded the initial audit report draft for Milestone 1.',
      timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      status: 'delivered',
      attachments: [
        {
          name: 'TaskChain_Audit_Draft_v1.pdf',
          url: '#',
          type: 'file',
          size: '1.4 MB',
        },
      ],
    },
  ],
  '102': [
    {
      id: 'msg_102_1',
      contractId: '102',
      senderId: 'freelancer_2',
      senderName: 'Marcus Chen',
      senderRole: 'freelancer',
      senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
      content: 'Hey Alex, I have set up the Next.js wallet provider with @stellar/freighter-api integration.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_102_2',
      contractId: '102',
      senderId: 'client_1',
      senderName: 'Alex Vance',
      senderRole: 'client',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      content: 'The Freighter wallet connection hook is working smoothly now!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      status: 'read',
    },
  ],
  '103': [
    {
      id: 'msg_103_1',
      contractId: '103',
      senderId: 'freelancer_1',
      senderName: 'Elena Rostova',
      senderRole: 'freelancer',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      content: 'Final escrow specs have been delivered.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_103_2',
      contractId: '103',
      senderId: 'client_2',
      senderName: 'Sarah Jenkins',
      senderRole: 'client',
      senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
      content: 'Funds have been released successfully. Thank you for working together!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      status: 'read',
    },
  ],
};
